In [ ]:
import numpy as np

In [44]:
d1 = np.array([1, 2, 3])
print(d1)

[1 2 3]


In [52]:
d2 = np.array([[1, 2], [2, 3], [3, 4]])
print(d2)

[[1 2]
 [2 3]
 [3 4]]


In [57]:
d3 = np.array([[[1, 2], [2, 3]], [[3, 4], [4, 5]]])
print(d3)

[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]


In [59]:
print(d1.ndim)
print(d2.ndim)
print(d3.ndim)

1
2
3


In [ ]:
lista1 = [1, 2, 3]
lista2 = [1, 2, 3]

resultado = lista1 + lista2
print(resultado)

[1, 2, 3, 1, 2, 3]


In [ ]:
lista1 = [1, 2, 3]
lista2 = [1, 2, 3]

resultado = [i + j for i, j in zip(lista1, lista2)]
print(resultado)

[2, 4, 6]


In [64]:
lista1 = np.array([1, 2, 3])
lista2 = np.array([1, 2, 3])

resultado = lista1 + lista2
print(resultado)

[2 4 6]


In [78]:
lista_np = np.array([[1, 2, 3], [3, 4, 5]])
print(lista_np)
print(lista_np[0, :])
print(lista_np[:, 0])

[[1 2 3]
 [3 4 5]]
[1 2 3]
[1 3]
